#!/usr/bin/env bash
#
# split-php.sh — Publish packages/php/ as a standalone Composer-installable repo.

set -euo pipefail

MONOREPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SPLIT_PREFIX="packages/php"
SPLIT_REMOTE_URL="https://github.com/kon2raya24/ph-bir-php.git"
EXPECTED_REPO_PATTERN="kon2raya24/ph-bir-php"

cd "$MONOREPO_ROOT"

if [ ! -d "$SPLIT_PREFIX" ] || [ ! -f "package.json" ] || [ ! -d "data" ]; then
  echo "ERROR: must be run from ph-bir monorepo root (cwd: $MONOREPO_ROOT)" >&2
  exit 1
fi

case "$SPLIT_REMOTE_URL" in
  *"$EXPECTED_REPO_PATTERN"*) ;;
  *)
    echo "ERROR: SPLIT_REMOTE_URL ($SPLIT_REMOTE_URL) does not match expected pattern '$EXPECTED_REPO_PATTERN'" >&2
    exit 1
    ;;
esac

if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: working tree has uncommitted changes. Commit or stash them first." >&2
  git status --short
  exit 1
fi

echo "==> Splitting $SPLIT_PREFIX history into a temp branch..."
SPLIT_BRANCH="__split-php-$(date +%s)"
git subtree split --prefix="$SPLIT_PREFIX" -b "$SPLIT_BRANCH" >/dev/null
echo "    split branch: $SPLIT_BRANCH"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"; git branch -D "$SPLIT_BRANCH" >/dev/null 2>&1 || true' EXIT
echo "==> Cloning split branch into temp work area..."
git clone --quiet --branch "$SPLIT_BRANCH" --single-branch "$MONOREPO_ROOT" "$TMP_DIR/split"

echo "==> Bundling data/*.json into split..."
mkdir -p "$TMP_DIR/split/data"
cp "$MONOREPO_ROOT"/data/*.json "$TMP_DIR/split/data/"

cd "$TMP_DIR/split"

if [ ! -f composer.json ] || [ ! -d src ] || [ ! -d tests ] || [ ! -d data ]; then
  echo "ERROR: unexpected split shape. Contents:" >&2
  ls -la >&2
  exit 1
fi

git add data/
if ! git diff --cached --quiet; then
  git commit --quiet -m "Bundle data files for standalone install

Auto-generated by scripts/split-php.sh from the ph-bir monorepo.
Source of truth: https://github.com/kon2raya24/ph-bir"
fi

echo "==> Force-pushing to $SPLIT_REMOTE_URL ..."
git remote remove origin 2>/dev/null || true
git remote add origin "$SPLIT_REMOTE_URL"
git push --quiet --force origin "HEAD:main"

echo ""
echo "✓ Split push complete."
echo "  Mirror: https://github.com/kon2raya24/ph-bir-php"
echo ""
echo "Next steps:"
echo "  1. Tag a release on the mirror, e.g.: git -C $TMP_DIR/split tag v0.1.0 && git -C $TMP_DIR/split push origin v0.1.0"
echo "  2. Submit (first time only) at https://packagist.org/packages/submit"
echo "     using URL: $SPLIT_REMOTE_URL"
